name: krishi_sathi
description: Your app description here

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  dio: ^5.4.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  record: ^5.0.0
  camera: ^0.10.5+9
  image: ^4.1.7
  get_it: ^7.6.7
  connectivity_plus: ^5.0.2
  flutter_carousel_intro: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true 