name: krishi_sathi
description: Your app description here

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_carousel_intro: 1.0.11
  dio: ^5.4.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  just_audio: ^0.10.4
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  camera: ^0.10.5+5
  image: ^4.1.7
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  # Remove manual versions of:
  # leak_tracker, leak_tracker_testing, etc. Let flutter_test handle them

flutter:
  uses-material-design: true
  assets:
    - assets/translations/en.json
    - assets/translations/ne.json
    - assets/images/app-logo.png
    - assets/images/card-1.png
    - assets/images/profile.png
    - assets/images/prompt.png
    - assets/icons/question.png
    - assets/icons/send.png
    - assets/icons/speaker.png
    

